### PR TITLE
Fix theorem 3.7 and 3.6

### PR DESCRIPTION
**Pull request by erehulka**
- Change proof of U2 in theorem 3.7, the former was incorrect,
- Exchange points 3 and 4 in theorem 3.6 and change the proof of one of them.

### CODE REVIEW

**Comment by japdlsd** [comment]
@dodo42 could you please look at that? :)

**Review by dodo42 — CHANGES_REQUESTED** [review]
Okrem tej jednej veci to vyzerá fajn.

**Comment by erehulka** [comment]
@dodo42 Asi si zabudol pridať koment k tej chybe :D

**Comment by erehulka** [comment]
@dodo42 skúsil som to nejak pomeniť, ak by ti to prišlo lepšie inak, tak kľudne asi môžeš upraviť.

**Pull request merged**
